### ISSUE TITLE
Code snippets for nested if/else statements

### ISSUE THREAD

**Issue by tlestang** [OxfordRSE/How-to-write-better-research-code-NTD-Technical-Meeting-2021#4]

**Comment by tlestang** [comment]
smelly function
```R
apply_vaccine_to_population <- function(population, nvaccines, threshold_age) {
    for (individual in population) {
        if (nvaccines > 0) {
            if (indiv["age"] > threshold_age || indiv["isAtRisk"]) {
                if (indiv["hasFirstJab"]) {
                    inject_second_jab(indiv)
                    nvaccines <- nvaccines - 1
                } else {
                    inject_first_jab(indiv)
                }
            }
        } else {
            return("No more doses")
        }
    }
}
```
Alternative
```R
eligible_to_vaccine <- function(individual, threshold_age) {
    in_target_age_group = indiv["age"] > threshold_age
    return(in_target_age_group || individual["isAtRisk"])
}

apply_vaccine_to_population <- function(population, nvaccines, threshold_age) {
    for (individual in population) {
        if (nvaccines == 0) { return("No more doses") }
        
        if (!eligible_to_vaccine(individual, threshold_age)) next
        
        if (indiv["hasFirstJab"]) {
            inject_second_jab(individual)
            nvaccines <- nvaccines - 1
        } else {
            inject_first_jab(individual)
        }
    }
}
```

**Comment by ben18785** [comment]
Looks really great. I can't best this. My thoughts are:

- Very minor but `||` considers only the first element of a vector (if a vector is passed); I might be tempted to use `|` since it would probably fail if (by mistake) vectors are passed. Because of this, I tend to use `|` (as I have done in my example).
- An epidemiological one: I'm not quite sure about why `nvaccines` declines only when people are given second jab? 1st and second vaccines are often (as in Covid) interchangeable... It's probably fine if you talk through it though.
- Also, maybe it's possible to have `inject_first_jab` that would modify an individual, but I can't think how to do it. More typical in R is the messier `individual <- inject_first_jab(individual)`. (But I can see why you might want to keep the former!)
- Sorry, another R specific thought: since R doesn't do pass by reference, your population of individuals wouldn't actually be modified by the code. So, you'd have to do something like create an empty population and append individuals to it...again, this depends on how much like working R we'd like these to be and I'm sure adding some "..." might go far enough
